---

substitutions:
  dev_id: kitchen-shutter
  dev_name: Jalousie Küche

packages:
  device_base: !include common/lanbon-l8hs.yaml

cover:
  - platform: time_based
    name: ${dev_name}
    device_class: shutter

    open_action:
      - switch.turn_off: relay2
      - switch.turn_on: relay1
    open_duration: 10sec

    close_action:
      - switch.turn_off: relay1
      - switch.turn_on: relay2
    close_duration: 10sec

    stop_action:
      - switch.turn_off: relay1
      - switch.turn_off: relay2

custom_component:
  - lambda: |-
      auto ui = new KitchenShutterUI();
      return {ui};
