esphome:
  name: $dev_id
  platform: ESP32
  board: esp32dev
  comment: $dev_name
  platformio_options: 
    platform: espressif32
    board: az-delivery-devkit-v4
    board_build.mcu: esp32
    board_build.f_cpu: 240000000L

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan

  # Enable fallback hotspot
  ap:
    ssid: "${dev_name} Fallback Hotspot"
    password: !secret wifi_ap_password

# Enable captive portal for emergency flashing
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

# Enable over-the-air updates
ota:
  password: !secret esphome_ota_password

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  - platform: version
    name: version
  - platform: wifi_info
    ip_address:
      id: ip
      name: ${dev_name} IP
    ssid:
      id: ssid
      name: ${dev_name} SSID
    bssid:
      id: bssid
      name: ${dev_name} BSSID
