---
esphome:
  name: $dev_id
  platform: ESP8266
  board: esp8285
  comment: $dev_name

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan

  # Enable fallback hotspot
  ap:
    ssid: "Coffeemachine Fallback Hotspot"
    password: !secret wifi_ap_password

# Enable captive portal for emergency flashing
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

# Enable over-the-air updates
ota:
  password: !secret esphome_ota_password

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  - platform: version
    name: version
  - platform: wifi_info
    ip_address:
      id: ip
      name: ${dev_name} IP
    ssid:
      id: ssid
      name: ${dev_name} SSID
    bssid:
      id: bssid
      name: ${dev_name} BSSID


binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    id: button
    name: ${dev_name} Button
    pin:
      number: GPIO3
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  # Switch to restart the plug
  - platform: restart
    id: restart_switch
    name: ${dev_name} Reboot
  # Switch to toggle the relay
  - platform: gpio
    id: relay
    name: ${dev_name}
    pin: GPIO14
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

output:
  # Relay state led
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO1
      inverted: true

light:
  # Relay state light
  - platform: monochromatic
    output: state_led
    id: led

# Uses the red LED as a status indicator
status_led:
  pin:
    number: GPIO13
    inverted: true

